language: erlang
notifications:
  recipients:
    - arnaud.wetzel@kbrwadventure.com
otp_release:
  - 17.0
  - 17.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
